/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CLERKFALLBACKURL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLERKSECRETKEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLERKSIGININURL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLERKSIGNUPURL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXTPUBLICKEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RGMscooper": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "ScoopedVideosTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WavBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}